import { randomBytes, randomUUID, createHash } from 'node:crypto';
import type { Pool } from 'pg';
import { z } from 'zod';
import type { EmailTemplate } from '../email/templates.js';

export const signupSchema = z.object({
  email: z.string().trim().max(254).email().transform(value => value.toLowerCase()),
  consent: z.literal(true),
  website: z.string().max(200).optional().default(''),
});
export const consentVersion = 'newsletter-v1';
export const consentText = 'Email me Oynk product news and updates. I can unsubscribe at any time.';

export function welcomeEmail(unsubscribeUrl: string): EmailTemplate {
  // URL is generated by the server, never from request headers or user input.
  const safeUrl = unsubscribeUrl.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
  return {
    subject: 'You’re on the Oynk list',
    text: `Welcome to Oynk.\n\nYou’ve joined our newsletter. We’ll keep you updated on the consumer app, network partnerships and product launches.\n\nIf you didn’t request this, or change your mind, unsubscribe here: ${unsubscribeUrl}\n\nThe Oynk team`,
    html: `<!doctype html><html lang="en"><body style="margin:0;background:#f4f6ef;font-family:Arial,sans-serif;color:#173b2c"><div style="max-width:520px;margin:32px auto;padding:32px;background:#fff;border-radius:20px"><p style="font-size:26px;font-weight:bold">Oynk</p><h1 style="font-size:28px">You’re on the list.</h1><p style="line-height:1.7">Thanks for joining the Oynk newsletter. We’ll keep you updated on the consumer app, network partnerships and product launches.</p><p style="line-height:1.7">We’re glad you’re here.<br>The Oynk team</p><p style="font-size:13px;line-height:1.6;color:#52665b">If you didn’t request this or change your mind, <a href="${safeUrl}" style="color:#275d43">unsubscribe here</a>.</p></div></body></html>`,
  };
}

export function createNewsletterService(db: Pool) {
  return {
    async allowRequest(ip: string): Promise<boolean> {
      const key = createHash('sha256').update(`newsletter:${ip}`).digest('hex');
      const result = await db.query<{ attempts: number }>(`INSERT INTO newsletter_rate_limits(key) VALUES($1)
        ON CONFLICT(key) DO UPDATE SET
        attempts = CASE WHEN newsletter_rate_limits.window_start < NOW()-INTERVAL '1 hour' THEN 1 ELSE newsletter_rate_limits.attempts+1 END,
        window_start = CASE WHEN newsletter_rate_limits.window_start < NOW()-INTERVAL '1 hour' THEN NOW() ELSE newsletter_rate_limits.window_start END
        RETURNING attempts`, [key]);
      return result.rows[0].attempts <= 10;
    },
    async subscribe(email: string): Promise<void> {
      await db.query(`INSERT INTO newsletter_subscribers(id,email,consent_version,unsubscribe_token) VALUES($1,$2,$3,$4)
        ON CONFLICT(email) DO UPDATE SET subscribed_at=NOW(),unsubscribed_at=NULL,consent_version=EXCLUDED.consent_version,
        delivery_status='pending',delivery_attempts=0,next_attempt_at=NOW(),lease_id=NULL,lease_until=NULL,confirmation_sent_at=NULL
        WHERE (newsletter_subscribers.unsubscribed_at IS NOT NULL OR newsletter_subscribers.delivery_status='failed')
        AND newsletter_subscribers.subscribed_at < NOW()-INTERVAL '1 day'`,
        [randomUUID(), email, consentVersion, randomBytes(32).toString('hex')]);
    },
    async unsubscribe(token: string): Promise<void> {
      await db.query(`UPDATE newsletter_subscribers SET unsubscribed_at=COALESCE(unsubscribed_at,NOW()) WHERE unsubscribe_token=$1`, [token]);
    },
    async deliver(send: (input: EmailTemplate & { to: string }) => Promise<void>, publicUrl: string, preview: boolean): Promise<void> {
      // Lease a single row so parallel API instances cannot normally deliver the same job.
      const lease = randomUUID();
      const result = await db.query<{id: string;email: string;unsubscribe_token: string;delivery_attempts: number}>(`
        UPDATE newsletter_subscribers SET delivery_status='sending',lease_id=$1,lease_until=NOW()+INTERVAL '15 minutes',delivery_attempts=delivery_attempts+1
        WHERE id=(SELECT id FROM newsletter_subscribers WHERE unsubscribed_at IS NULL AND
          ((delivery_status='pending' AND next_attempt_at<=NOW()) OR (delivery_status='sending' AND lease_until<NOW()))
          ORDER BY next_attempt_at LIMIT 1 FOR UPDATE SKIP LOCKED)
        RETURNING id,email,unsubscribe_token,delivery_attempts`, [lease]);
      const row = result.rows[0];
      if (!row) return;
      try {
        const url = new URL('/api/newsletter/unsubscribe', publicUrl);
        url.searchParams.set('token', row.unsubscribe_token);
        await send({to: row.email, ...welcomeEmail(url.href)});
        await db.query(`UPDATE newsletter_subscribers SET delivery_status=$3,confirmation_sent_at=CASE WHEN $3='sent' THEN NOW() ELSE NULL END,lease_id=NULL,lease_until=NULL WHERE id=$1 AND lease_id=$2`, [row.id, lease, preview ? 'previewed' : 'sent']);
      } catch {
        await db.query(`UPDATE newsletter_subscribers SET delivery_status=$3,next_attempt_at=NOW()+INTERVAL '15 minutes',lease_id=NULL,lease_until=NULL WHERE id=$1 AND lease_id=$2`, [row.id,lease,row.delivery_attempts>=5 ? 'failed' : 'pending']);
        console.warn('[newsletter] Confirmation email deferred; no subscriber data logged');
      }
    },
    async cleanup(): Promise<void> {
      await db.query("DELETE FROM newsletter_rate_limits WHERE window_start<NOW()-INTERVAL '2 hours'");
    },
  };
}
