import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import type { OrganizationSummary } from '@oynk/shared';
import { Activity, ArrowDownLeft, ArrowUpRight, Check, ChevronRight, CircleDollarSign, Clock3, ExternalLink, Filter, Landmark, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Target, Users, Waypoints, X } from 'lucide-react';
import { api, ApiError, type ProtocolOverview, type RampPolicy, type RampTransaction, type RampTransactionDetail } from '../api';
import type { ConsoleRoute } from '../consoleRoutes';
import { WalletConnection } from '../wallet';

const usdc=(atomic:string|null|undefined)=>atomic===null||atomic===undefined?'—':`${(Number(atomic)/1e7).toLocaleString(undefined,{maximumFractionDigits:2})} USDC`;
const money=(minor:string|null|undefined,currency='NGN')=>minor===null||minor===undefined?'—':new Intl.NumberFormat('en-NG',{style:'currency',currency,maximumFractionDigits:2}).format(Number(minor)/100);
const short=(value:string)=>`${value.slice(0,7)}…${value.slice(-6)}`;
const date=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
function State({value}:{value:string}){return <span className={`control-state state-${value.toLowerCase().replaceAll('_','-')}`}>{value.replaceAll('_',' ')}</span>;}
function transactionName(tx:RampTransaction){if(tx.direction==='OFF_RAMP')return'Naira withdrawal';if(tx.intentState==='quoted'||tx.intentState==='expired')return'Deposit quote';return'Naira deposit';}
function transactionState(tx:RampTransaction){if(tx.state==='CREATED'&&tx.intentState)return tx.intentState.toUpperCase();return tx.state;}
function Loading(){return <div className="control-loading"><RefreshCw/><span>Loading verified platform state…</span></div>;}
function Failure({message,retry}:{message:string;retry:()=>void}){return <div className="control-failure"><X/><div><strong>Couldn’t load this view</strong><p>{message}</p></div><button onClick={retry}>Try again</button></div>;}

export function ControlPanel({organization,route}:{organization:OrganizationSummary;route:ConsoleRoute}){
 const segment=route.path.split('/').at(-1);
 if(segment==='protocol'||segment==='home')return <ProtocolPage organization={organization}/>;
 if(segment==='policies')return <PoliciesPage organization={organization}/>;
 if(segment==='settlements')return <SettlementNetworkPage/>;
 return <TransactionsPage organization={organization} approvalsOnly={segment==='approvals'}/>;
}

function ProtocolPage({organization}:{organization:OrganizationSummary}){
 const[data,setData]=useState<ProtocolOverview>();const[metrics,setMetrics]=useState<any>();const[transactions,setTransactions]=useState<RampTransaction[]>([]);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[loading,setLoading]=useState(true);const[rebalancing,setRebalancing]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[p,m,t]=await Promise.all([api.protocol(),api.rampMetrics(),api.rampTransactions({limit:'6'})]);setData(p);setMetrics(m);setTransactions(t.transactions);}catch(e){setError(e instanceof ApiError?e.message:'Platform state is unavailable.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const pending=useMemo(()=>metrics?.series?.filter((x:any)=>x.approval_state==='PENDING').reduce((n:number,x:any)=>n+Number(x.count),0)??0,[metrics]);
 const canManage=organization.permissions.includes('ramp_policies:manage');
 const required=data?.rebalancing.differenceAtomic?BigInt(data.rebalancing.differenceAtomic):0n;const requiredMagnitude=required<0n?-required:required;
 async function createRebalance(){if(!requiredMagnitude||rebalancing)return;setRebalancing(true);setError('');setNotice('');try{const order=await api.createRebalanceOrder({amountAtomic:requiredMagnitude.toString(),minimumFillAtomic:(requiredMagnitude<10_000_000n?requiredMagnitude:10_000_000n).toString()});setNotice(`Rebalancing order ${short(order.requestId)} is open for provider fills.`);await load();}catch(e){setError(e instanceof ApiError?e.message:'The rebalancing order could not be created.');}finally{setRebalancing(false);}}
 if(loading&&!data)return <Loading/>;if(error&&!data)return <Failure message={error} retry={()=>void load()}/>;
 const vault=data?.vault.totalAtomic;
 return <div className="control-page"><div className="control-hero"><div><p className="eyebrow">Control center</p><h1>Protocol operations</h1><p>Live contract state, liquidity and ramp activity across the Oynk protocol.</p></div><div className="control-hero-actions"><WalletConnection/><button className="control-refresh" onClick={()=>void load()} aria-label="Refresh protocol state"><RefreshCw/></button></div></div>{notice?<div className="control-notice"><Check/>{notice}</div>:null}{error?<Failure message={error} retry={()=>void load()}/>:null}
  <section className="control-metrics"><article><span><CircleDollarSign/>Available liquidity</span><strong>{usdc(data?.vault.availableAtomic)}</strong><small>{usdc(vault)} total in the shared vault</small></article><article><span><Landmark/>Pool claims</span><strong>{usdc(data?.pool.totalUnitsAtomic)}</strong><small>{data?.pool.depositorCount??'—'} active depositors</small></article><article><span><ShieldCheck/>Oynk buffer</span><strong>{usdc(data?.vault.bufferAtomic)}</strong><small>Team-owned withdrawal protection</small></article><article><span><Clock3/>Pending redemptions</span><strong>{usdc(data?.pool.pendingRedemptionsAtomic)}</strong><small>{pending} ramp approvals awaiting review</small></article></section>
  <div className="control-grid"><section className="control-panel"><header><div><h2>Contract state</h2><p>Configured Soroban contracts for this environment.</p></div><State value={data?.network??organization.platformMode}/></header><div className="contract-list">{data&&Object.entries(data.contracts).map(([name,value])=><a href={value.explorerUrl} target="_blank" rel="noreferrer" key={name}><span className="contract-icon">{name==='vault'?<Landmark/>:name==='pool'?<Users/>:<Activity/>}</span><div><strong>{name.replaceAll(/([A-Z])/g,' $1')}</strong><small title={value.address}>{short(value.address)}</small></div><State value={value.status}/><ExternalLink/></a>)}</div></section>
   <section className="control-panel"><header><div><h2>Ramp rates</h2><p>Contract-authoritative NGN rates.</p></div><div className="header-states"><State value={data?.rates.status??'unavailable'}/>{data?.rates.version?<span className="version">v{data.rates.version}</span>:null}</div></header><div className="rate-list"><div><span>On-ramp</span><strong>{data?.rates.onrampFiatPerUsdc?money(data.rates.onrampFiatPerUsdc):'—'}</strong><small>per 1 USDC</small></div><div><span>Off-ramp</span><strong>{data?.rates.offrampFiatPerUsdc?money(data.rates.offrampFiatPerUsdc):'—'}</strong><small>per 1 USDC</small></div></div><div className="ledger-note"><span>Latest ledger</span><strong>{data?.latestLedger?.toLocaleString()??'Unavailable'}</strong><span>Valid until</span><strong>{data?.rates.validUntilLedger?.toLocaleString()??'—'}</strong></div></section></div>
  <section className="control-panel rebalance-panel"><header><div><h2>Vault rebalancing</h2><p>Actual user liquidity obligations plus deposited Oynk buffer, compared with available USDC.</p></div><State value={data?.rebalancing.status??'unavailable'}/></header><div className="rebalance-grid"><div><span><Target/>Expected liquidity</span><strong>{usdc(data?.rebalancing.targetAtomic)}</strong></div><div><span><Activity/>Available liquidity</span><strong>{usdc(data?.vault.availableAtomic)}</strong></div><div><span><Waypoints/>Rebalance required</span><strong>{requiredMagnitude?usdc(requiredMagnitude.toString()):data?.rebalancing.differenceAtomic==='0'?'Balanced':'—'}</strong></div><div><span><Landmark/>RWA utilization</span><strong>{data?.pool.totalUnitsAtomic&&data?.pool.rwaDeployedAtomic?`${(Number(data.pool.rwaDeployedAtomic)*100/Math.max(1,Number(data.pool.totalUnitsAtomic))).toFixed(1)}%`:'0.0%'}</strong></div></div>{data?.rebalancing.status==='unconfigured'?<p className="configuration-callout">Configure the Oynk provider before creating vault-liquidity orders.</p>:requiredMagnitude?<div className="rebalance-action"><div><strong>Open a provider order</strong><p>{required<0n?'Restore USDC owed to the Vault':'Route surplus Vault USDC'} through the existing provider settlement flow. Partial fills are enabled.</p></div><button onClick={()=>void createRebalance()} disabled={!canManage||rebalancing}>{rebalancing?'Creating order…':'Create rebalance order'}</button></div>:<p className="configuration-callout balanced">Available liquidity covers current user obligations and deposited buffer. No action is required.</p>}</section>
  <TransactionTable transactions={transactions} title="Recent ramp activity" subtitle="Latest on-ramp and off-ramp records."/>
 </div>;
}

function showValue(value:unknown):string{if(value===null||value===undefined)return'—';if(typeof value==='object')return JSON.stringify(value);return String(value).replaceAll('_',' ');}
function RecordDetails({value}:{value:Record<string,unknown>}){return <dl className="network-record">{Object.entries(value).map(([key,item])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd title={showValue(item)}>{showValue(item)}</dd></div>)}</dl>;}
function SettlementNetworkPage(){
 const[requestId,setRequestId]=useState('');const[fillId,setFillId]=useState('');const[operator,setOperator]=useState('');const[sourceCurrency,setSourceCurrency]=useState('566');const[destinationCurrency,setDestinationCurrency]=useState('0');const[result,setResult]=useState<{title:string;value:Record<string,unknown>;ledger:number}>();const[error,setError]=useState('');const[loading,setLoading]=useState(false);
 async function lookup(task:()=>Promise<{latestLedger:number;settlement?:Record<string,unknown>;fill?:Record<string,unknown>;rate?:Record<string,unknown>;provider?:Record<string,unknown>}>,title:string){setLoading(true);setError('');try{const value=await task();setResult({title,value:(value.settlement??value.fill??value.rate??value.provider)!,ledger:value.latestLedger});}catch(e){setResult(undefined);setError(e instanceof ApiError?e.message:'The contract record is unavailable.');}finally{setLoading(false);}}
 return <div className="control-page"><div className="control-hero"><div><p className="eyebrow">Settlement network</p><h1>Orders and providers</h1><p>Inspect provider settlements, partial fills, corridor rates and registered-provider limits directly from Soroban state.</p></div><WalletConnection/></div>{error?<Failure message={error} retry={()=>setError('')}/>:null}<div className="network-tools"><form className="control-panel lookup-card" onSubmit={e=>{e.preventDefault();void lookup(()=>fillId?api.settlementFill(requestId.trim(),fillId.trim()):api.settlement(requestId.trim()),fillId?'Settlement fill':'Settlement order');}}><header><div><h2>Settlement order</h2><p>Use the 32-byte request ID. Add a fill ID to inspect a partial fill.</p></div><Waypoints/></header><label><span>Request ID</span><input value={requestId} onChange={e=>setRequestId(e.target.value)} minLength={64} maxLength={64} required placeholder="64-character hexadecimal ID"/></label><label><span>Fill ID <small>optional</small></span><input value={fillId} onChange={e=>setFillId(e.target.value)} maxLength={64} placeholder="Partial-fill identifier"/></label><button disabled={loading}>Inspect contract state</button></form><form className="control-panel lookup-card" onSubmit={e=>{e.preventDefault();void lookup(()=>api.corridor(Number(sourceCurrency),Number(destinationCurrency)),'Corridor rate');}}><header><div><h2>Corridor rate</h2><p>Zero identifies USDC; fiat uses ISO-4217 numeric codes.</p></div><CircleDollarSign/></header><div className="lookup-pair"><label><span>Source</span><input inputMode="numeric" value={sourceCurrency} onChange={e=>setSourceCurrency(e.target.value)} required/></label><label><span>Destination</span><input inputMode="numeric" value={destinationCurrency} onChange={e=>setDestinationCurrency(e.target.value)} required/></label></div><button disabled={loading}>Read corridor rate</button></form><form className="control-panel lookup-card" onSubmit={e=>{e.preventDefault();void lookup(()=>api.provider(operator.trim()),'Registered provider');}}><header><div><h2>Provider registry</h2><p>Inspect capabilities, exposure and operating limits.</p></div><Users/></header><label><span>Provider address</span><input value={operator} onChange={e=>setOperator(e.target.value)} required placeholder="G…"/></label><button disabled={loading}>Inspect provider</button></form></div>{loading?<Loading/>:result?<section className="control-panel result-panel"><header><div><h2>{result.title}</h2><p>Verified at ledger {result.ledger.toLocaleString()}.</p></div><State value="on-chain"/></header><RecordDetails value={result.value}/></section>:null}</div>;
}

function TransactionsPage({organization,approvalsOnly}:{organization:OrganizationSummary;approvalsOnly:boolean}){
 const[transactions,setTransactions]=useState<RampTransaction[]>([]);const[selected,setSelected]=useState<RampTransaction>();const[detail,setDetail]=useState<RampTransactionDetail>();const[detailLoading,setDetailLoading]=useState(false);const[query,setQuery]=useState('');const[direction,setDirection]=useState('');const[state,setState]=useState('');const[approvalState,setApprovalState]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(true);
 const[decision,setDecision]=useState<'approve'|'reject'>();const[decisionNote,setDecisionNote]=useState('');const[deciding,setDeciding]=useState(false);
 const canApprove=organization.permissions.includes('ramp_transactions:approve');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const result=approvalsOnly?await api.rampApprovals():await api.rampTransactions({query:query||undefined,direction:direction||undefined,state:state||undefined,approvalState:approvalState||undefined,limit:'100'});setTransactions(result.transactions);}catch(e){setError(e instanceof ApiError?e.message:'Transactions are unavailable.');}finally{setLoading(false);}},[approvalsOnly,query,direction,state,approvalState]);
 useEffect(()=>{void load();},[load]);
 async function submitDecision(){if(!selected||!decision)return;setDeciding(true);setError('');try{await api.decideRamp(selected.id,decision,decisionNote.trim()||undefined);setSelected(undefined);setDecision(undefined);setDecisionNote('');await load();}catch(e){setError(e instanceof ApiError?e.message:'The decision could not be recorded.');}finally{setDeciding(false);}}
 async function inspect(value:RampTransaction){setSelected(value);setDetail(undefined);setDetailLoading(true);setError('');try{setDetail(await api.rampTransaction(value.id));}catch(e){setError(e instanceof ApiError?e.message:'Transaction activity is unavailable.');}finally{setDetailLoading(false);}}
 function closeDrawer(){setSelected(undefined);setDetail(undefined);setDecision(undefined);setDecisionNote('');}
 return <div className="control-page"><div className="control-hero"><div><p className="eyebrow">{approvalsOnly?'Review queue':'Transaction ledger'}</p><h1>{approvalsOnly?'Manual approvals':'Ramp transactions'}</h1><p>{approvalsOnly?'Review policy-triggered transactions before funds are released.':'Search and inspect every on-ramp and off-ramp lifecycle.'}</p></div><WalletConnection/></div>
 {!approvalsOnly?<div className="control-filters"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reference, provider or hash"/></label><label><Filter/><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="">All directions</option><option value="ON_RAMP">On-ramp</option><option value="OFF_RAMP">Off-ramp</option></select></label><label><select aria-label="Transaction status" value={state} onChange={e=>setState(e.target.value)}><option value="">All statuses</option>{['CREATED','PENDING_APPROVAL','APPROVED','PROCESSING','COMPLETED','FAILED','REJECTED','CANCELLED'].map(value=><option key={value}>{value}</option>)}</select></label><label><select aria-label="Approval status" value={approvalState} onChange={e=>setApprovalState(e.target.value)}><option value="">All approvals</option>{['NOT_REQUIRED','PENDING','APPROVED','REJECTED'].map(value=><option key={value}>{value}</option>)}</select></label><button onClick={()=>void load()}><RefreshCw/>Refresh</button></div>:null}
 {error?<Failure message={error} retry={()=>void load()}/>:loading?<Loading/>:<TransactionTable transactions={transactions} title={approvalsOnly?'Pending decisions':'All transactions'} subtitle={`${transactions.length} record${transactions.length===1?'':'s'} in this view.`} onSelect={value=>void inspect(value)}/>} 
 {selected?<div className="control-drawer-backdrop" onClick={closeDrawer}><aside className="control-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={closeDrawer} aria-label="Close transaction details"><X/></button><p className="eyebrow">Transaction detail</p><h2>{selected.direction.replace('_',' ')}</h2><State value={selected.state}/><dl><dt>Reference</dt><dd>{selected.reference}</dd><dt>Amount</dt><dd>{usdc(selected.usdcAmountAtomic)}</dd><dt>Fiat</dt><dd>{money(selected.fiatAmountMinor,selected.fiatCurrency??'NGN')}</dd><dt>Provider</dt><dd>{selected.provider??'Unassigned'}</dd><dt>Provider reference</dt><dd>{selected.providerReference??'—'}</dd><dt>Approval</dt><dd>{selected.approvalState.replaceAll('_',' ')}</dd><dt>Risk</dt><dd>{selected.riskState.replaceAll('_',' ')}</dd><dt>Stellar transaction</dt><dd>{selected.stellarTransactionHash??'—'}</dd><dt>Created</dt><dd>{date(selected.createdAt)}</dd></dl>{detailLoading?<div className="drawer-loading"><RefreshCw/>Loading audit activity…</div>:detail?<section className="activity-timeline"><h3>Activity</h3>{detail.events.map(item=><article key={item.sequence}><span/><div><strong>{item.eventType.replaceAll('_',' ')}</strong><small>{date(item.createdAt)} · {item.actorType.replaceAll('_',' ')}</small>{item.toState?<State value={item.toState}/>:null}</div></article>)}</section>:null}{selected.approvalState==='PENDING'&&canApprove?<>{decision?<div className={`decision-panel ${decision}`}><strong>{decision==='approve'?'Approve transaction':'Reject transaction'}</strong><p>{decision==='approve'?'Confirm that this transaction may proceed to execution.':'Rejecting ends this transaction and prevents execution.'}</p><label><span>Operator note <small>optional</small></span><textarea value={decisionNote} onChange={event=>setDecisionNote(event.target.value)} maxLength={1000} placeholder="Add context for the audit trail" autoFocus/></label><div><button className="decision-cancel" onClick={()=>{setDecision(undefined);setDecisionNote('');}} disabled={deciding}>Cancel</button><button className={`decision-confirm ${decision}`} onClick={()=>void submitDecision()} disabled={deciding}>{deciding?'Recording…':decision==='approve'?'Confirm approval':'Confirm rejection'}</button></div></div>:<div className="drawer-actions"><button className="reject" onClick={()=>setDecision('reject')}>Reject</button><button className="approve" onClick={()=>setDecision('approve')}><Check/>Approve</button></div>}</>:null}</aside></div>:null}
 </div>;
}

function TransactionTable({transactions,title,subtitle,onSelect}:{transactions:RampTransaction[];title:string;subtitle:string;onSelect?:(value:RampTransaction)=>void}){return <section className="control-panel transaction-panel"><header><div><h2>{title}</h2><p>{subtitle}</p></div></header>{transactions.length?<div className="transaction-table"><div className="transaction-head"><span>Direction</span><span>Reference</span><span>Amount</span><span>Status</span><span>Created</span><span/></div>{transactions.map(tx=><button key={tx.id} onClick={()=>onSelect?.(tx)} disabled={!onSelect}><span className={`direction-icon ${tx.direction==='ON_RAMP'?'in':'out'}`}>{tx.direction==='ON_RAMP'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><span><strong>{transactionName(tx)}</strong><small>{short(tx.reference)}</small></span><span><strong>{usdc(tx.usdcAmountAtomic)}</strong><small>{money(tx.fiatAmountMinor,tx.fiatCurrency??'NGN')}</small></span><span><State value={transactionState(tx)}/></span><span>{date(tx.createdAt)}</span><span>{onSelect?<ChevronRight/>:null}</span></button>)}</div>:<div className="control-empty"><ShieldCheck/><h3>Nothing needs attention</h3><p>New ramp transactions will appear here with their policy and approval state.</p></div>}</section>;}

function PoliciesPage({organization}:{organization:OrganizationSummary}){const[policies,setPolicies]=useState<RampPolicy[]>([]);const[error,setError]=useState('');const[notice,setNotice]=useState('');const canManage=organization.permissions.includes('ramp_policies:manage');const load=useCallback(()=>api.rampPolicies().then(x=>setPolicies(x.policies)).catch(e=>setError(e instanceof ApiError?e.message:'Policies are unavailable.')),[]);useEffect(()=>{void load();},[load]);async function submit(event:FormEvent<HTMLFormElement>,policy:RampPolicy){event.preventDefault();setError('');setNotice('');const f=new FormData(event.currentTarget);try{await api.updateRampPolicy(policy.direction,{enabled:f.get('enabled')==='on',manualThresholdUsdcAtomic:String(Math.round(Number(f.get('threshold'))*1e7)),cumulativeEnabled:f.get('cumulativeEnabled')==='on',cumulativeThresholdUsdcAtomic:f.get('cumulativeThreshold')?String(Math.round(Number(f.get('cumulativeThreshold'))*1e7)):null,cumulativeWindowSeconds:f.get('windowHours')?Math.round(Number(f.get('windowHours'))*3600):null,note:String(f.get('note')||'')});setNotice(`${policy.direction.replace('_',' ')} policy updated.`);await load();}catch(e){setError(e instanceof ApiError?e.message:'Policy update failed.');}}
 return <div className="control-page"><div className="control-hero"><div><p className="eyebrow">Policy controls</p><h1>Ramp thresholds</h1><p>Define automatic processing and manual-review boundaries without changing execution code.</p></div><WalletConnection/></div>{notice?<div className="control-notice"><Check/>{notice}</div>:null}{error?<Failure message={error} retry={()=>void load()}/>:null}<div className="policy-grid">{policies.map(policy=><form className="control-panel policy-card" key={policy.id} onSubmit={e=>void submit(e,policy)}><header><div><span className={`direction-icon ${policy.direction==='ON_RAMP'?'in':'out'}`}>{policy.direction==='ON_RAMP'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><h2>{policy.direction.replace('_',' ')}</h2><p>Policy version {policy.version}</p></div></div><label className="control-switch"><input name="enabled" type="checkbox" defaultChecked={policy.enabled} disabled={!canManage}/><span/></label></header><label><span>Manual approval above</span><div className="policy-input"><input name="threshold" type="number" min="0" step="0.01" defaultValue={Number(policy.manualThresholdUsdcAtomic)/1e7} disabled={!canManage}/><em>USDC</em></div><small>Amounts equal to this value can process automatically. Greater amounts require review.</small></label><label className="policy-check"><input name="cumulativeEnabled" type="checkbox" defaultChecked={policy.cumulativeEnabled} disabled={!canManage}/><span>Enable cumulative velocity review</span></label><div className="policy-pair"><label><span>Cumulative amount</span><div className="policy-input"><input name="cumulativeThreshold" type="number" min="0" step="0.01" defaultValue={policy.cumulativeThresholdUsdcAtomic?Number(policy.cumulativeThresholdUsdcAtomic)/1e7:''} disabled={!canManage}/><em>USDC</em></div></label><label><span>Window</span><div className="policy-input"><input name="windowHours" type="number" min="1" step="1" defaultValue={policy.cumulativeWindowSeconds?policy.cumulativeWindowSeconds/3600:''} disabled={!canManage}/><em>hours</em></div></label></div><label><span>Change note</span><input name="note" placeholder="Reason for this change" disabled={!canManage}/></label><button className="policy-save" disabled={!canManage}><SlidersHorizontal/>Save policy</button>{!canManage?<small className="policy-readonly">Your role has read-only policy access.</small>:null}</form>)}</div></div>;
}
