import { createContext,useCallback,useContext,useMemo,useState,type ReactNode } from "react";
import { AlertTriangle,CheckCircle2,Info,X } from "lucide-react";
export type ToastKind="success"|"error"|"warning"|"info";
export type ToastItem={id:string;kind:ToastKind;message:string;persistent?:boolean};
type ToastApi={show:(kind:ToastKind,message:string,options?:{persistent?:boolean})=>void;success:(message:string)=>void;error:(message:string,options?:{persistent?:boolean})=>void;warning:(message:string)=>void;info:(message:string)=>void;dismiss:(id:string)=>void};
const Context=createContext<ToastApi|null>(null);
export function addToast(items:readonly ToastItem[],item:ToastItem):ToastItem[]{if(items.some((current)=>current.kind===item.kind&&current.message===item.message))return[...items];return[...items,item].slice(-4);}
export function ToastProvider({children}:{children:ReactNode}){const[items,setItems]=useState<ToastItem[]>([]);const dismiss=useCallback((id:string)=>setItems((current)=>current.filter((item)=>item.id!==id)),[]);const show=useCallback((kind:ToastKind,message:string,options?:{persistent?:boolean})=>{const id=crypto.randomUUID();setItems((current)=>addToast(current,{id,kind,message,persistent:options?.persistent}));if(!options?.persistent)setTimeout(()=>dismiss(id),kind==="error"?8000:kind==="warning"?6000:kind==="info"?5000:4000);},[dismiss]);const api=useMemo<ToastApi>(()=>({show,success:(message)=>show("success",message),error:(message,options)=>show("error",message,options),warning:(message)=>show("warning",message),info:(message)=>show("info",message),dismiss}),[show,dismiss]);return <Context.Provider value={api}>{children}<div className="toast-region" aria-label="Notifications">{items.map((item)=>{const Icon=item.kind==="success"?CheckCircle2:item.kind==="info"?Info:AlertTriangle;return <div key={item.id} className={`toast ${item.kind}`} role={item.kind==="error"?"alert":"status"} aria-live={item.kind==="error"?"assertive":"polite"}><Icon aria-hidden="true"/><span>{item.message}</span><button onClick={()=>dismiss(item.id)} aria-label="Dismiss notification"><X/></button></div>;})}</div></Context.Provider>}
export function useToast():ToastApi{const value=useContext(Context);if(!value)throw new Error("useToast must be used inside ToastProvider");return value;}
