import type { BusinessComplianceProfile, OtpChallengeResponse, SessionResponse } from "@oynk/shared";

export type RampTransaction={id:string;reference:string;direction:'ON_RAMP'|'OFF_RAMP';state:string;intentState:string|null;approvalState:string;riskState:string;fiatCurrency:string|null;fiatAmountMinor:string|null;usdcAmountAtomic:string|null;provider:string|null;providerReference:string|null;stellarTransactionHash:string|null;failureCode:string|null;createdAt:string;updatedAt:string};
export type RampEvent={sequence:number;eventType:string;fromState:string|null;toState:string|null;actorType:string;actorReference:string|null;requestId:string|null;details:Record<string,unknown>;createdAt:string};
export type RampTransactionDetail={transaction:RampTransaction&{walletAddress:string;network:string;providerStatus:string|null;failureReason:string|null;completedAt:string|null;policyVersion:number;policySnapshot:Record<string,unknown>;metadata:Record<string,unknown>};events:RampEvent[];policyDecisions:Array<{outcome:string;reasonCodes:string[];createdAt:string}>;approvals:Array<{action:string;operatorUserId:string;note:string|null;createdAt:string}>;executionAttempts:Array<{operation:string;attemptNumber:number;state:string;providerReference:string|null;stellarTransactionHash:string|null;errorCode:string|null;startedAt:string|null;finishedAt:string|null;createdAt:string}>};
export type RampPolicy={id:string;direction:'ON_RAMP'|'OFF_RAMP';enabled:boolean;manualThresholdUsdcAtomic:string;cumulativeEnabled:boolean;cumulativeThresholdUsdcAtomic:string|null;cumulativeWindowSeconds:number|null;additionalRules:Record<string,unknown>;version:number;updatedAt?:string};
export type ProtocolOverview={network:'TESTNET'|'PUBLIC';asset:{symbol:string;contract:string;decimals:number};fetchedAt:string;latestLedger:number|null;contracts:Record<string,{address:string;status:string;explorerUrl:string}>;balances:Record<string,{status:string;atomic:string|null}>;vault:{totalAtomic:string|null;reservedAtomic:string|null;availableAtomic:string|null;bufferAtomic:string|null;userAvailableAtomic:string|null;status:string};pool:{status:string;totalContributedAtomic:string|null;totalUnitsAtomic:string|null;depositorCount:number|null;pendingRedemptionsAtomic?:string|null;rwaDeployedAtomic?:string|null;maxRwaUtilizationBps?:number|null};rates:{status:string;onrampFiatPerUsdc?:string;offrampFiatPerUsdc?:string;validUntilLedger?:number;updatedLedger?:number;version?:string};rebalancing:{status:string;provider:string|null;targetAtomic:string|null;differenceAtomic:string|null;recommendation:string}};
export type RebalanceOrder={id:string;network:string;requestId:string;direction:string;amountAtomic:string;minimumFillAtomic:string;state:string;stellarTransactionHash:string;createdAt?:string};
export type SettlementLookup={network:'TESTNET'|'PUBLIC';latestLedger:number;requestId:string;settlement:Record<string,unknown>};
export type SettlementFillLookup={network:'TESTNET'|'PUBLIC';latestLedger:number;requestId:string;fillId:string;fill:Record<string,unknown>};
export type CorridorLookup={network:'TESTNET'|'PUBLIC';latestLedger:number;sourceCurrency:number;destinationCurrency:number;rate:Record<string,unknown>};
export type ProviderLookup={network:'TESTNET'|'PUBLIC';latestLedger:number;operator:string;provider:Record<string,unknown>};

const API_URL=(import.meta.env?.VITE_API_URL??"").replace(/\/$/,"");
let activeCsrfToken="";
export class ApiError extends Error { constructor(message:string,public readonly status:number,public readonly code?:string,public readonly fieldErrors?:Record<string,string>,public readonly details?:unknown,public readonly requestId?:string){super(message);this.name="ApiError";} }
function safeMessage(status:number,code?:string):string{if(code==="ACCOUNT_EXISTS"||status===409)return"An account already exists with this email address.";if(code==="INVALID_CREDENTIALS")return"The email or password is incorrect.";if(code==="OTP_INVALID")return"The verification code is incorrect or has expired.";if(status===400||status===422)return"Some information needs your attention.";if(status===401)return"Your session has expired. Sign in again.";if(status===403)return"You don’t have permission to complete this action.";if(status===429)return"Too many attempts. Try again shortly.";return"We couldn’t complete this request. Try again, or contact support if the problem continues.";}
export function normalizeApiError(status:number,payload:unknown):ApiError{if(typeof payload!=="object"||payload===null)return new ApiError(safeMessage(status),status);const value=payload as Record<string,unknown>;const code=typeof value.code==="string"?value.code:undefined;const fieldErrors=typeof value.fieldErrors==="object"&&value.fieldErrors!==null?Object.fromEntries(Object.entries(value.fieldErrors).filter((entry):entry is [string,string]=>typeof entry[1]==="string")):undefined;const requestId=typeof value.requestId==="string"?value.requestId:undefined;const serverMessage=typeof value.error==="string"&&!value.error.toLowerCase().includes("stack")?value.error:undefined;const message=status>=500?safeMessage(status,code):serverMessage??safeMessage(status,code);return new ApiError(message,status,code,fieldErrors,value.details,requestId);}
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const method=options.method??"GET";let response:Response;try{response=await fetch(`${API_URL}${path}`,{...options,credentials:"include",headers:{"Content-Type":"application/json",...(method!=="GET"&&method!=="HEAD"&&activeCsrfToken?{"x-csrf-token":activeCsrfToken}:{}),...options.headers}});}catch{throw new ApiError("We couldn’t connect to Oynk. Check your connection and try again.",0,"NETWORK_ERROR");}if(!response.ok){const payload:unknown=await response.json().catch(()=>null);throw normalizeApiError(response.status,payload);}if(response.status===204){activeCsrfToken="";return undefined as T;}const payload=await response.json() as T;if(typeof payload==="object"&&payload!==null&&"csrfToken" in payload&&typeof payload.csrfToken==="string")activeCsrfToken=payload.csrfToken;return payload;}
export const api={
  session:()=>request<SessionResponse>("/api/auth/session"),
  login:(email:string,password:string)=>request<OtpChallengeResponse>("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})}),
  signup:(type:"business"|"partner",body:Record<string,unknown>)=>request<OtpChallengeResponse>(`/api/auth/signup/${type}`,{method:"POST",body:JSON.stringify(body)}),
  verifyEmail:(challengeId:string,code:string)=>request<{verified:true}>("/api/auth/verify-email",{method:"POST",body:JSON.stringify({challengeId,code})}),
  verifySignIn:(challengeId:string,code:string)=>request<SessionResponse>("/api/auth/verify-otp",{method:"POST",body:JSON.stringify({challengeId,code})}),
  resendOtp:(challengeId:string)=>request<OtpChallengeResponse>("/api/auth/otp/resend",{method:"POST",body:JSON.stringify({challengeId})}),
  forgotPassword:(email:string)=>request<{accepted:true;challenge?:OtpChallengeResponse}>("/api/auth/forgot-password",{method:"POST",body:JSON.stringify({email})}),
  resetPassword:(challengeId:string|null,code:string,password:string)=>request<{reset:true}>("/api/auth/reset-password",{method:"POST",body:JSON.stringify({challengeId,code,password})}),
  selectOrganization:(organizationId:string)=>request<SessionResponse>("/api/auth/session/organization",{method:"POST",body:JSON.stringify({organizationId})}),
  logout:()=>request<void>("/api/auth/logout",{method:"POST",body:"{}"}),
  businessCompliance:()=>request<BusinessComplianceProfile>("/api/compliance/business"),
  saveBusinessCompliance:(profile:Omit<BusinessComplianceProfile,"status"|"updatedAt">)=>request<BusinessComplianceProfile>("/api/compliance/business",{method:"PUT",body:JSON.stringify(profile)}),
  protocol:()=>request<ProtocolOverview>('/api/control/ramps/protocol'),
  createRebalanceOrder:(body:Record<string,string>)=>request<RebalanceOrder>('/api/control/ramps/rebalancing/orders',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)}),
  rampMetrics:()=>request<{generatedAt:string;series:Array<{direction:string;state:string;approval_state:string;count:number;usdcAmountAtomic:string}>}>('/api/control/ramps/metrics'),
  rampTransactions:(filters:Record<string,string|undefined>={})=>{const query=new URLSearchParams(Object.entries(filters).filter((entry):entry is [string,string]=>Boolean(entry[1])));return request<{transactions:RampTransaction[]}>(`/api/control/ramps/transactions?${query}`);},
  rampTransaction:(id:string)=>request<RampTransactionDetail>(`/api/control/ramps/transactions/${encodeURIComponent(id)}`),
  rampApprovals:()=>request<{transactions:RampTransaction[]}>('/api/control/ramps/approvals'),
  rampPolicies:()=>request<{policies:RampPolicy[]}>('/api/control/ramps/policies'),
  decideRamp:(id:string,action:'approve'|'reject',note?:string)=>request<RampTransaction>(`/api/control/ramps/transactions/${encodeURIComponent(id)}/${action}`,{method:'POST',body:JSON.stringify({note})}),
  updateRampPolicy:(direction:string,body:Record<string,unknown>)=>request<RampPolicy>(`/api/control/ramps/policies/${direction}`,{method:'PUT',body:JSON.stringify(body)}),
  settlement:(requestId:string)=>request<SettlementLookup>(`/api/control/ramps/settlements/${encodeURIComponent(requestId)}`),
  settlementFill:(requestId:string,fillId:string)=>request<SettlementFillLookup>(`/api/control/ramps/settlements/${encodeURIComponent(requestId)}/fills/${encodeURIComponent(fillId)}`),
  corridor:(sourceCurrency:number,destinationCurrency:number)=>request<CorridorLookup>(`/api/control/ramps/corridors/${sourceCurrency}/${destinationCurrency}`),
  provider:(operator:string)=>request<ProviderLookup>(`/api/control/ramps/providers/${encodeURIComponent(operator)}`),
};
