import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import type { OrganizationSummary, OrganizationType, OtpChallengeResponse, SessionResponse } from "@oynk/shared";
import { Activity, AlertTriangle, ArrowRight, BookOpen, Building2, ChevronDown, ClipboardList, CreditCard, Droplets, Landmark, LockKeyhole, LogOut, Menu, Network, ScrollText, Settings, ShieldAlert, ShieldCheck, UserRound, Users, WalletCards, X } from "lucide-react";
import { api, ApiError } from "./api";
import { ConsoleSection } from "./components/ConsoleSection";
import { BusinessCompliancePage } from "./components/BusinessCompliancePage";
import { BrandMark } from "./components/BrandMark";
import { getConsoleRoute, getConsoleRoutes, type ConsoleRoute } from "./consoleRoutes";
import { EnhancedForgotPassword, EnhancedLogin, EnhancedResetPassword, EnhancedSignup, EnhancedSignupChoice, EnhancedVerifyOtp } from "./forms/AuthForms";

type Navigate=(path:string)=>void;
function navigate(path:string):void{history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}
function usePath():string{const[path,setPath]=useState(location.pathname);useEffect(()=>{const update=()=>setPath(location.pathname);addEventListener("popstate",update);return()=>removeEventListener("popstate",update);},[]);return path;}
function ErrorMessage({message}:{message:string|null}){return message?<div className="error" role="alert"><AlertTriangle size={17}/><span>{message}</span></div>:null;}
function ResendCode({challenge}:{challenge:OtpChallengeResponse}){const[message,setMessage]=useState<string|null>(null);async function resend(){try{const next=await api.resendOtp(challenge.challengeId);sessionStorage.setItem("oynk_challenge",JSON.stringify(next));setMessage("A new code was issued. Reloading…");setTimeout(()=>location.reload(),500);}catch(cause){setMessage(cause instanceof ApiError?cause.message:"A new code could not be issued.");}}return <div className="resend"><button type="button" onClick={()=>void resend()}>Send a new code</button>{message?<span role="status">{message}</span>:null}</div>;}
function Field({label,name,type="text",required=true,autoComplete,children}:{label:string;name:string;type?:string;required?:boolean;autoComplete?:string;children?:ReactNode}){return <label className="field"><span>{label}</span>{children??<input name={name} type={type} required={required} autoComplete={autoComplete}/>}</label>;}
function AuthFrame({eyebrow,title,subtitle,children}:{eyebrow:string;title:string;subtitle:string;children:ReactNode}){return <main className="auth-page"><section className="auth-brand"><a className="logo" href={import.meta.env.VITE_PUBLIC_SITE_URL??"http://localhost:5173"}><BrandMark/><span>Oynk</span></a><div><p className="eyebrow">Payment infrastructure</p><h2>Operate money movement with clarity.</h2><p>Secure access for businesses, settlement partners, and Oynk operations teams.</p></div><ul><li><ShieldCheck/>Two-step sign-in</li><li><Network/>Organization-scoped access</li><li><LockKeyhole/>Server-managed sessions</li></ul></section><section className="auth-panel"><div className="auth-card"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subtitle">{subtitle}</p>{children}</div><footer>Protected by Oynk security controls · <a href={import.meta.env.VITE_DOCS_URL??"https://docs.oynk.io"} target="_blank" rel="noopener noreferrer">Documentation</a></footer></section></main>;}
function Login(){const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError(null);const data=new FormData(event.currentTarget);try{const challenge=await api.login(String(data.get("email")),String(data.get("password")));sessionStorage.setItem("oynk_challenge",JSON.stringify(challenge));const requested=new URLSearchParams(location.search).get("returnTo");if(requested?.startsWith("/")&&!requested.startsWith("//")&&!requested.includes("\\"))sessionStorage.setItem("oynk_return_to",requested);navigate("/verify-otp");}catch(cause){setError(cause instanceof ApiError?cause.message:"We couldn't start sign-in.");}finally{setBusy(false);}}return <AuthFrame eyebrow="Secure sign in" title="Access Oynk Console" subtitle="Enter your credentials. We’ll send a one-time code after your password is verified."><form onSubmit={submit}><Field label="Work email" name="email" type="email" autoComplete="email"/><Field label="Password" name="password" type="password" autoComplete="current-password"/><div className="form-link"><a href="/forgot-password">Forgot password?</a></div><ErrorMessage message={error}/><button className="primary" disabled={busy}>{busy?"Checking credentials…":"Continue securely"}<ArrowRight/></button></form><div className="divider"><span>New to Oynk?</span></div><a className="secondary" href="/signup">Create or apply for an account</a></AuthFrame>;}
function SignupChoice(){return <AuthFrame eyebrow="Get started" title="Choose your account" subtitle="Oynk separates business payment operations from settlement-provider participation."><div className="choice-grid"><a href="/signup/business"><Building2/><strong>Create a business account</strong><span>Collect payments, make payouts, manage settlement and prepare for terminal access.</span><em>Start in sandbox <ArrowRight/></em></a><a href="/signup/partner"><Landmark/><strong>Apply as a settlement partner</strong><span>Submit your organization for review to support approved liquidity and settlement operations.</span><em>Application required <ArrowRight/></em></a></div><p className="legal-note">Partner registration does not guarantee approval or network activation.</p><a className="text-link" href="/login">Already have an account? Sign in</a></AuthFrame>;}
function Signup({type}:{type:"business"|"partner"}){const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError(null);const form=new FormData(event.currentTarget);const body=Object.fromEntries(form.entries());try{const challenge=await api.signup(type,{...body,acceptedTerms:form.get("acceptedTerms")==="on"});sessionStorage.setItem("oynk_challenge",JSON.stringify(challenge));sessionStorage.setItem("oynk_verification_kind","email");navigate("/verify-otp");}catch(cause){setError(cause instanceof ApiError?cause.message:"We couldn't create the account.");}finally{setBusy(false);}}const partner=type==="partner";return <AuthFrame eyebrow={partner?"Partner application":"Business account"} title={partner?"Apply to join the network":"Create your Oynk account"} subtitle={partner?"Provide verified organization details. Activation follows compliance and operational review.":"Start in sandbox while your business verification is completed."}><form onSubmit={submit}><div className="form-grid"><Field label="First name" name="firstName" autoComplete="given-name"/><Field label="Last name" name="lastName" autoComplete="family-name"/></div><Field label="Work email" name="email" type="email" autoComplete="email"/><Field label="Phone number" name="phone" type="tel" autoComplete="tel"/><Field label="Legal business name" name="legalName" autoComplete="organization"/><Field label="Trading name (optional)" name="tradingName" required={false}/><div className="form-grid"><Field label="Registration country" name="registrationCountry"><input name="registrationCountry" required maxLength={2} placeholder="US" aria-describedby="country-hint"/></Field><Field label="Operating country" name="operatingCountry"><input name="operatingCountry" required maxLength={2} placeholder="NG" aria-describedby="country-hint"/></Field></div><p id="country-hint" className="hint">Use the two-letter ISO country code.</p><div className="form-grid"><Field label="Password" name="password" type="password" autoComplete="new-password"/><Field label="Confirm password" name="confirmPassword" type="password" autoComplete="new-password"/></div><p className="hint">Use at least 12 characters with uppercase, lowercase, and a number.</p><label className="check"><input type="checkbox" name="acceptedTerms" required/><span>I agree to the applicable terms and privacy notice.</span></label><ErrorMessage message={error}/><button className="primary" disabled={busy}>{busy?"Creating account…":partner?"Submit account details":"Create business account"}<ArrowRight/></button></form><a className="text-link" href="/signup">Choose a different account type</a></AuthFrame>;}
function VerifyOtp({onSignedIn}:{onSignedIn:(session:SessionResponse)=>void}){const stored=sessionStorage.getItem("oynk_challenge");const challenge=stored?JSON.parse(stored) as OtpChallengeResponse:null;const kind=sessionStorage.getItem("oynk_verification_kind");const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);if(!challenge)return <AuthFrame eyebrow="Verification" title="No active challenge" subtitle="Start again to request a new security code."><a className="primary" href="/login">Return to sign in</a></AuthFrame>;const activeChallenge=challenge;async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError(null);const code=String(new FormData(event.currentTarget).get("code"));try{if(kind==="email"){await api.verifyEmail(activeChallenge.challengeId,code);sessionStorage.removeItem("oynk_verification_kind");sessionStorage.removeItem("oynk_challenge");navigate("/login");}else{const session=await api.verifySignIn(activeChallenge.challengeId,code);sessionStorage.removeItem("oynk_challenge");onSignedIn(session);const requested=sessionStorage.getItem("oynk_return_to");sessionStorage.removeItem("oynk_return_to");navigate(requested??homeFor(session.organization));}}catch(cause){setError(cause instanceof ApiError?cause.message:"We couldn't verify the code.");}finally{setBusy(false);}}return <AuthFrame eyebrow="Email verification" title="Enter your six-digit code" subtitle={`We sent a code to ${activeChallenge.destinationHint}. It expires shortly.`}><form onSubmit={submit}><Field label="Verification code" name="code"><input className="otp" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required autoFocus/></Field>{activeChallenge.developmentCode?<div className="dev-code"><strong>Development mail preview</strong><span>{activeChallenge.developmentCode}</span></div>:null}<ErrorMessage message={error}/><button className="primary" disabled={busy}>{busy?"Verifying…":kind==="email"?"Verify email":"Complete sign in"}</button><ResendCode challenge={activeChallenge}/></form></AuthFrame>;}
function ForgotPassword(){const[message,setMessage]=useState<string|null>(null);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const result=await api.forgotPassword(String(new FormData(event.currentTarget).get("email")));if(result.challenge){sessionStorage.setItem("oynk_reset_challenge",JSON.stringify(result.challenge));navigate("/reset-password");}else setMessage("If the account exists, password reset instructions have been sent.");}return <AuthFrame eyebrow="Account recovery" title="Reset your password" subtitle="Enter your email. We’ll send a time-limited verification code when the account is eligible."><form onSubmit={submit}><Field label="Work email" name="email" type="email" autoComplete="email"/>{message?<div className="notice">{message}</div>:null}<button className="primary">Send reset code</button></form><a className="text-link" href="/login">Return to sign in</a></AuthFrame>;}
function ResetPassword(){const stored=sessionStorage.getItem("oynk_reset_challenge");const storedChallenge=stored?JSON.parse(stored) as OtpChallengeResponse:null;const queryChallenge=new URLSearchParams(location.search).get("challenge");const challenge=storedChallenge??(queryChallenge?{challengeId:queryChallenge,purpose:"PASSWORD_RESET",expiresAt:"",resendAvailableAt:"",destinationHint:"your email address"} satisfies OtpChallengeResponse:null);const[error,setError]=useState<string|null>(null);if(!challenge)return <ForgotPassword/>;const activeChallenge=challenge;async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);try{await api.resetPassword(activeChallenge.challengeId,String(data.get("code")),String(data.get("password")));sessionStorage.removeItem("oynk_reset_challenge");navigate("/login");}catch(cause){setError(cause instanceof ApiError?cause.message:"Password reset failed.");}}return <AuthFrame eyebrow="Account recovery" title="Choose a new password" subtitle={`Enter the code sent to ${activeChallenge.destinationHint} and a new password.`}><form onSubmit={submit}><Field label="Verification code" name="code"><input className="otp" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required/></Field>{activeChallenge.developmentCode?<div className="dev-code"><strong>Development mail preview</strong><span>{activeChallenge.developmentCode}</span></div>:null}<Field label="New password" name="password" type="password" autoComplete="new-password"/><ErrorMessage message={error}/><button className="primary">Reset password</button></form></AuthFrame>;}
function homeFor(organization:OrganizationSummary|null):string{return organization?.type==="BUSINESS"?"/business/home":organization?.type==="SETTLEMENT_PARTNER"?"/partner/home":organization?.type==="INTERNAL"?"/internal/home":"/organizations";}
function navigationGroup(type:OrganizationType,path:string):string{if(path.endsWith("/home"))return"Overview";if(type==="BUSINESS")return path.endsWith("/team")||path.endsWith("/settings")?"Organization":"Money movement";if(type==="SETTLEMENT_PARTNER")return path.endsWith("/organization")?"Organization":"Settlement network";return path.endsWith("/risk-alerts")||path.endsWith("/audit-logs")||path.endsWith("/indexing")?"Oversight":"Platform";}
function navigationIcon(route:ConsoleRoute){const segment=route.path.split("/").at(-1);if(segment==="home")return <WalletCards/>;if(segment==="payments"||segment==="payouts"||segment==="point-of-sale"||segment==="terminals")return <CreditCard/>;if(segment==="cross-border"||segment==="corridors")return <Network/>;if(segment==="settlements"||segment==="execution")return <Landmark/>;if(segment==="team"||segment==="businesses"||segment==="partners"||segment==="organization")return <Users/>;if(segment==="settings")return <Settings/>;if(segment==="liquidity")return <Droplets/>;if(segment==="applications"||segment==="opportunities")return <ClipboardList/>;if(segment==="risk-alerts")return <ShieldAlert/>;if(segment==="audit-logs")return <ScrollText/>;return <Activity/>;}
function ConsoleShell({session,setSession,path}:{session:SessionResponse;setSession:(session:SessionResponse|null)=>void;path:string}){
  const[mobileNavigationOpen,setMobileNavigationOpen]=useState(false);
  const sidebarRef=useRef<HTMLElement>(null);
  const menuButtonRef=useRef<HTMLButtonElement>(null);
  const organization=session.organization;

  useEffect(()=>{
    if(!mobileNavigationOpen)return;
    const sidebar=sidebarRef.current;
    if(!sidebar)return;
    const previousOverflow=document.body.style.overflow;
    document.body.style.overflow="hidden";
    const focusable=()=>Array.from(sidebar.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])'));
    focusable()[0]?.focus();
    function handleKeyDown(event:KeyboardEvent){
      if(event.key==="Escape"){
        event.preventDefault();
        setMobileNavigationOpen(false);
        return;
      }
      if(event.key!=="Tab")return;
      const elements=focusable();
      if(elements.length===0)return;
      const first=elements[0];
      const last=elements[elements.length-1];
      if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}
      else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}
    }
    function handleBreakpoint(event:MediaQueryListEvent){if(event.matches)setMobileNavigationOpen(false);}
    const desktopQuery=window.matchMedia("(min-width: 768px)");
    document.addEventListener("keydown",handleKeyDown);
    desktopQuery.addEventListener("change",handleBreakpoint);
    return()=>{
      document.body.style.overflow=previousOverflow;
      document.removeEventListener("keydown",handleKeyDown);
      desktopQuery.removeEventListener("change",handleBreakpoint);
      if(window.matchMedia("(max-width: 767px)").matches)menuButtonRef.current?.focus();
    };
  },[mobileNavigationOpen]);

  if(!organization)return <OrganizationChoice session={session} setSession={setSession}/>;
  const nav=getConsoleRoutes(organization.type);
  const activeRoute=getConsoleRoute(organization.type,path)??nav[0];
  async function logout(){await api.logout();setSession(null);navigate("/login");}
  async function changeOrganization(id:string){const next=await api.selectOrganization(id);setSession(next);navigate(homeFor(next.organization));}

  return <div className="console">
    <aside ref={sidebarRef} id="console-navigation" className={mobileNavigationOpen?"sidebar open":"sidebar"} aria-label="Console navigation">
      <div className="sidebar-head"><span className="logo light"><BrandMark/><span>Oynk</span></span><button className="icon mobile-navigation-control" onClick={()=>setMobileNavigationOpen(false)} aria-label="Close navigation" aria-expanded={mobileNavigationOpen} aria-controls="console-navigation"><X/></button></div>
      <div className="org-block"><span>{organization.name}</span><small>{organization.type.replaceAll("_"," ")}</small></div>
      <nav aria-label="Primary navigation">{Array.from(new Set(nav.map((item)=>navigationGroup(organization.type,item.path)))).map((group)=><section className="sidebar-nav-group" key={group}><h2>{group}</h2>{nav.filter((item)=>navigationGroup(organization.type,item.path)===group).map((item)=><a key={item.path} href={item.path} className={item.path===activeRoute.path?"active":""} aria-current={item.path===activeRoute.path?"page":undefined} onClick={(event)=>{event.preventDefault();navigate(item.path);setMobileNavigationOpen(false);}}>{navigationIcon(item)}<span>{item.label}</span></a>)}</section>)}</nav>
      <a className="docs-link" href={import.meta.env.VITE_DOCS_URL??"https://docs.oynk.io"} target="_blank" rel="noopener noreferrer"><BookOpen/>Documentation</a>
    </aside>
    <button className={mobileNavigationOpen?"navigation-overlay open":"navigation-overlay"} onClick={()=>setMobileNavigationOpen(false)} aria-label="Close navigation" tabIndex={-1}/>
    <div className="workspace">
      <header>
        <div className="header-context"><button ref={menuButtonRef} className="icon mobile-navigation-control" onClick={()=>setMobileNavigationOpen(true)} aria-label="Open navigation" aria-expanded={mobileNavigationOpen} aria-controls="console-navigation"><Menu/></button><div><small>{organization.type.replaceAll("_"," ")}</small><strong>{activeRoute.title}</strong></div></div>
        <div className="header-actions"><div className="mode"><span></span>{organization.platformMode}</div>{session.organizations.length>1?<label className="org-select"><span className="sr-only">Active organization</span><select value={organization.id} onChange={(event)=>void changeOrganization(event.target.value)}>{session.organizations.map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>:null}<div className="user-menu"><UserRound/><div><strong>{session.user.firstName} {session.user.lastName}</strong><small>{organization.role.replaceAll("_"," ")}</small></div><ChevronDown/></div><button className="icon" onClick={logout} aria-label="Sign out"><LogOut/></button></div>
      </header>
      <main><StatusBanner organization={organization}/>{activeRoute.path.endsWith("/compliance")?<BusinessCompliancePage organization={organization}/>:<ConsoleSection organization={organization} route={activeRoute}/>}</main>
    </div>
  </div>;
}
function StatusBanner({organization}:{organization:OrganizationSummary}){if(organization.type==="INTERNAL"&&organization.status==="ACTIVE")return <div className="banner info"><ShieldCheck/><div><strong>Internal operations access</strong><p>Actions are permission-scoped and recorded in the audit trail.</p></div></div>;if(organization.status==="SUSPENDED"||organization.status==="REJECTED"||organization.status==="CLOSED")return <div className="banner danger"><AlertTriangle/><div><strong>Organization access is restricted.</strong><p>Payment operations are unavailable. Contact Oynk support for the current account decision.</p></div></div>;const review=organization.status==="UNDER_REVIEW"||organization.status==="COMPLIANCE_SUBMITTED";const verificationPath=organization.type==="BUSINESS"?"/business/compliance":"/partner/compliance";return <div className={`banner ${review?"info":"attention"}`}><AlertTriangle/><div><strong>{review?"Your application is under review.":"Account verification is required for live operations."}</strong><p>{review?"Oynk will notify your organization when review status changes.":`This ${organization.platformMode.toLowerCase()} workspace remains restricted until review and activation are complete.`}</p></div>{review?null:<a href={verificationPath} onClick={(event)=>{event.preventDefault();navigate(verificationPath);}}>Complete verification</a>}</div>;}
function OrganizationChoice({session,setSession}:{session:SessionResponse;setSession:(session:SessionResponse|null)=>void}){async function choose(id:string){setSession(await api.selectOrganization(id));navigate(homeFor((await api.session()).organization));}return <AuthFrame eyebrow="Organization access" title="Choose an organization" subtitle="Your permissions and platform mode are scoped to the selected organization."><div className="organizations">{session.organizations.map((organization)=><button key={organization.id} onClick={()=>choose(organization.id)}><Building2/><span><strong>{organization.name}</strong><small>{organization.type.replaceAll("_"," ")} · {organization.role.replaceAll("_"," ")}</small></span><ArrowRight/></button>)}</div></AuthFrame>;}
function AccessDenied(){return <AuthFrame eyebrow="Access denied" title="This workspace is not available" subtitle="Your account does not have permission to open this route."><a className="primary" href="/login">Return to sign in</a></AuthFrame>;}
export function App(){const path=usePath();const[session,setSession]=useState<SessionResponse|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{api.session().then(setSession).catch(()=>setSession(null)).finally(()=>setLoading(false));},[]);if(path==="/login")return <EnhancedLogin/>;if(path==="/signup")return <EnhancedSignupChoice/>;if(path==="/signup/business")return <EnhancedSignup type="business"/>;if(path==="/signup/partner")return <EnhancedSignup type="partner"/>;if(path==="/verify-otp")return <EnhancedVerifyOtp onSignedIn={setSession}/>;if(path==="/forgot-password")return <EnhancedForgotPassword/>;if(path==="/reset-password")return <EnhancedResetPassword/>;if(path==="/access-denied")return <AccessDenied/>;if(path==="/invitation")return <AuthFrame eyebrow="Invitation" title="Organization invitations" subtitle="Invitation acceptance is not available for this account yet."><a className="primary" href="/login">Return to sign in</a></AuthFrame>;if(loading)return <div className="loading"><span className="logo">oynk<span>.</span></span><p>Securing your workspace…</p></div>;if(!session){const returnTo=path.startsWith("/")&&!path.startsWith("//")?path:"/";location.replace(`/login?returnTo=${encodeURIComponent(returnTo)}`);return null;}const expected=homeFor(session.organization);if(path==="/"||path==="/organizations"){if(session.organization){navigate(expected);return null;}return <OrganizationChoice session={session} setSession={setSession}/>;}if(!session.organization||!getConsoleRoute(session.organization.type,path))return <AccessDenied/>;return <ConsoleShell session={session} setSession={setSession} path={path}/>;}
