import { randomUUID } from 'node:crypto';
import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { getSessionByToken, verifyCsrf } from '../auth/authService.js';
import { config } from '../config.js';
import { decideRampTransaction, getRampTransaction, listRampPolicies, listRampTransactions, rampMetrics, RampError, retryRampTransaction, updateRampPolicy } from './service.js';
import { canUseRampControl } from './state.js';
import { corridorRate, createVaultRebalanceOrder, protocolOverview, providerSettlement, registeredProvider, settlementFill } from './protocol.js';
import { pool } from '../db/pool.js';

export const rampControlRouter = Router();
type Permission = 'ramp_transactions:read'|'ramp_transactions:approve'|'ramp_transactions:retry'|'ramp_policies:manage';
function sessionToken(request:Request):string|null{for(const part of(request.headers.cookie??'').split(';')){const[name,...value]=part.trim().split('=');if(name===config.AUTH_SESSION_COOKIE_NAME)return decodeURIComponent(value.join('='));}return null;}
function requestId(request:Request):string{return typeof request.headers['x-request-id']==='string'?request.headers['x-request-id']:randomUUID();}
async function context(request:Request,response:Response,permission:Permission,csrf=false){const token=sessionToken(request);const session=token?await getSessionByToken(token):null;if(!token||!session?.organization){response.status(401).json({error:'Authentication is required.',code:'UNAUTHENTICATED'});return null;}if(!canUseRampControl(session.organization.type,session.organization.permissions,permission)){response.status(403).json({error:'You do not have permission to perform this operation.',code:'PERMISSION_DENIED'});return null;}if(csrf){const value=typeof request.headers['x-csrf-token']==='string'?request.headers['x-csrf-token']:'';if(!value||!(await verifyCsrf(token,value))){response.status(403).json({error:'The security token is missing or invalid.',code:'CSRF_INVALID'});return null;}}return{session,organization:session.organization};}

const querySchema=z.object({direction:z.enum(['ON_RAMP','OFF_RAMP']).optional(),state:z.enum(['CREATED','POLICY_CHECK','PENDING_APPROVAL','APPROVED','PROCESSING','COMPLETED','FAILED','REJECTED','CANCELLED']).optional(),approvalState:z.enum(['NOT_REQUIRED','PENDING','APPROVED','REJECTED']).optional(),provider:z.string().trim().min(1).max(80).optional(),query:z.string().trim().min(1).max(160).optional(),limit:z.coerce.number().int().min(1).max(100).optional(),offset:z.coerce.number().int().min(0).optional()});
rampControlRouter.get('/transactions',async(req,res,next)=>{try{if(!await context(req,res,'ramp_transactions:read'))return;const parsed=querySchema.safeParse(req.query);if(!parsed.success){res.status(400).json({error:'Invalid transaction filters.',code:'VALIDATION_ERROR'});return;}res.json({transactions:await listRampTransactions(parsed.data)});}catch(e){next(e);}});
rampControlRouter.get('/transactions/:id',async(req,res,next)=>{try{if(!await context(req,res,'ramp_transactions:read'))return;res.json(await getRampTransaction(String(req.params.id)));}catch(e){next(e);}});
rampControlRouter.get('/approvals',async(req,res,next)=>{try{if(!await context(req,res,'ramp_transactions:read'))return;res.json({transactions:await listRampTransactions({approvalState:'PENDING',limit:Number(req.query.limit)||50})});}catch(e){next(e);}});
const decisionSchema=z.object({note:z.string().trim().max(1000).optional()});
for(const [path,action] of [['approve','APPROVE'],['reject','REJECT']] as const)rampControlRouter.post(`/transactions/:id/${path}`,async(req,res,next)=>{try{const current=await context(req,res,'ramp_transactions:approve',true);if(!current)return;const parsed=decisionSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:'The approval note is invalid.',code:'VALIDATION_ERROR'});return;}res.json(await decideRampTransaction({transactionId:String(req.params.id),action,operatorUserId:current.session.user.id,operatorOrganizationId:current.organization.id,note:parsed.data.note,requestId:requestId(req)}));}catch(e){next(e);}});
rampControlRouter.post('/transactions/:id/retry',async(req,res,next)=>{try{const current=await context(req,res,'ramp_transactions:retry',true);if(!current)return;const key=req.header('idempotency-key');if(!key||key.length<16||key.length>160){res.status(400).json({error:'A valid Idempotency-Key header is required.',code:'IDEMPOTENCY_KEY_REQUIRED'});return;}res.status(202).json(await retryRampTransaction({transactionId:String(req.params.id),idempotencyKey:key,operatorUserId:current.session.user.id,requestId:requestId(req)}));}catch(e){next(e);}});
rampControlRouter.get('/policies',async(req,res,next)=>{try{if(!await context(req,res,'ramp_transactions:read'))return;res.json({policies:await listRampPolicies()});}catch(e){next(e);}});
const atomic=z.string().regex(/^\d+$/).transform(BigInt);
const policySchema=z.object({enabled:z.boolean(),manualThresholdUsdcAtomic:atomic,cumulativeEnabled:z.boolean(),cumulativeThresholdUsdcAtomic:z.union([atomic,z.null()]),cumulativeWindowSeconds:z.number().int().min(60).max(31_536_000).nullable(),additionalRules:z.record(z.string(),z.unknown()).optional(),note:z.string().trim().max(1000).optional()}).superRefine((value,ctx)=>{if(value.cumulativeEnabled&&(value.cumulativeThresholdUsdcAtomic===null||value.cumulativeWindowSeconds===null))ctx.addIssue({code:'custom',path:['cumulativeEnabled'],message:'Cumulative threshold and window are required.'});});
rampControlRouter.put('/policies/:direction',async(req,res,next)=>{try{const current=await context(req,res,'ramp_policies:manage',true);if(!current)return;const direction=String(req.params.direction).toUpperCase();if(direction!=='ON_RAMP'&&direction!=='OFF_RAMP'){res.status(400).json({error:'Invalid ramp direction.',code:'VALIDATION_ERROR'});return;}const parsed=policySchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:'Review the policy configuration.',code:'VALIDATION_ERROR',fieldErrors:parsed.error.flatten().fieldErrors});return;}res.json(await updateRampPolicy({...parsed.data,direction,operatorUserId:current.session.user.id,operatorOrganizationId:current.organization.id,requestId:requestId(req)}));}catch(e){next(e);}});
rampControlRouter.get('/metrics',async(req,res,next)=>{try{if(!await context(req,res,'ramp_transactions:read'))return;res.json(await rampMetrics());}catch(e){next(e);}});
rampControlRouter.get('/protocol',async(req,res,next)=>{try{const current=await context(req,res,'ramp_transactions:read');if(!current)return;res.json(await protocolOverview(current.organization.platformMode==='LIVE'?'PUBLIC':'TESTNET'));}catch(e){next(e);}});
const rebalanceSchema=z.object({amountAtomic:z.string().regex(/^\d+$/).optional(),minimumFillAtomic:z.string().regex(/^\d+$/).optional()});
rampControlRouter.post('/rebalancing/orders',async(req,res,next)=>{try{const current=await context(req,res,'ramp_policies:manage',true);if(!current)return;const key=req.header('idempotency-key');if(!key||key.length<16||key.length>160){res.status(400).json({error:'A valid Idempotency-Key header is required.',code:'IDEMPOTENCY_KEY_REQUIRED'});return;}const parsed=rebalanceSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:'Review the rebalancing amount.',code:'VALIDATION_ERROR'});return;}const existing=await pool.query(`SELECT * FROM vault_rebalance_orders WHERE idempotency_key=$1`,[key]);if(existing.rows[0]){res.status(existing.rows[0].state==='OPEN'?200:202).json(existing.rows[0]);return;}const id=randomUUID();const network=controlNetwork(current.organization.platformMode);await pool.query(`INSERT INTO vault_rebalance_orders(id,idempotency_key,network,state,created_by,organization_id) VALUES($1,$2,$3,'SUBMITTING',$4,$5)`,[id,key,network,current.session.user.id,current.organization.id]);try{const order=await createVaultRebalanceOrder(network,parsed.data.amountAtomic?BigInt(parsed.data.amountAtomic):undefined,parsed.data.minimumFillAtomic?BigInt(parsed.data.minimumFillAtomic):undefined);await pool.query(`UPDATE vault_rebalance_orders SET request_id=$2,direction=$3,amount_atomic=$4,minimum_fill_atomic=$5,state='OPEN',stellar_transaction_hash=$6,updated_at=NOW() WHERE id=$1`,[id,order.requestId,order.direction,order.amountAtomic,order.minimumFillAtomic,order.transactionHash]);await pool.query(`INSERT INTO audit_logs(id,actor_user_id,organization_id,action,resource_type,resource_id,result,request_id,metadata) VALUES($1,$2,$3,'VAULT_REBALANCE_CREATED','VAULT_REBALANCE',$4,'SUCCESS',$5,$6)`,[randomUUID(),current.session.user.id,current.organization.id,id,requestId(req),order]);res.status(201).json({id,...order});}catch(error){const reason=error instanceof Error?error.message:'Rebalancing failed';await pool.query(`UPDATE vault_rebalance_orders SET state='FAILED',failure_reason=$2,updated_at=NOW() WHERE id=$1`,[id,reason]);throw error;}}catch(e){next(e);}});
rampControlRouter.get('/rebalancing/orders',async(req,res,next)=>{try{if(!await context(req,res,'ramp_transactions:read'))return;const result=await pool.query(`SELECT id,network,request_id AS "requestId",direction,amount_atomic::TEXT AS "amountAtomic",minimum_fill_atomic::TEXT AS "minimumFillAtomic",state,stellar_transaction_hash AS "stellarTransactionHash",failure_reason AS "failureReason",created_at AS "createdAt" FROM vault_rebalance_orders ORDER BY created_at DESC LIMIT 50`);res.json({orders:result.rows});}catch(e){next(e);}});
const bytes32Schema=z.string().regex(/^[0-9a-f]{64}$/i);
const stellarAddressSchema=z.string().regex(/^G[A-Z2-7]{55}$/);
function controlNetwork(mode:string){return mode==='LIVE'?'PUBLIC' as const:'TESTNET' as const;}
rampControlRouter.get('/settlements/:requestId',async(req,res,next)=>{try{const current=await context(req,res,'ramp_transactions:read');if(!current)return;const requestId=bytes32Schema.safeParse(String(req.params.requestId));if(!requestId.success){res.status(400).json({error:'Enter a valid 32-byte settlement request ID.',code:'VALIDATION_ERROR'});return;}const result=await providerSettlement(controlNetwork(current.organization.platformMode),requestId.data);if(!result.settlement){res.status(404).json({error:'Settlement order not found.',code:'NOT_FOUND'});return;}res.json(result);}catch(e){next(e);}});
rampControlRouter.get('/settlements/:requestId/fills/:fillId',async(req,res,next)=>{try{const current=await context(req,res,'ramp_transactions:read');if(!current)return;const parsed=z.object({requestId:bytes32Schema,fillId:bytes32Schema}).safeParse(req.params);if(!parsed.success){res.status(400).json({error:'Enter valid 32-byte settlement and fill IDs.',code:'VALIDATION_ERROR'});return;}const result=await settlementFill(controlNetwork(current.organization.platformMode),parsed.data.requestId,parsed.data.fillId);if(!result.fill){res.status(404).json({error:'Settlement fill not found.',code:'NOT_FOUND'});return;}res.json(result);}catch(e){next(e);}});
rampControlRouter.get('/corridors/:sourceCurrency/:destinationCurrency',async(req,res,next)=>{try{const current=await context(req,res,'ramp_transactions:read');if(!current)return;const parsed=z.object({sourceCurrency:z.coerce.number().int().min(0).max(999),destinationCurrency:z.coerce.number().int().min(0).max(999)}).safeParse(req.params);if(!parsed.success||parsed.data.sourceCurrency===parsed.data.destinationCurrency){res.status(400).json({error:'Enter two different ISO-4217 numeric currency codes.',code:'VALIDATION_ERROR'});return;}const result=await corridorRate(controlNetwork(current.organization.platformMode),parsed.data.sourceCurrency,parsed.data.destinationCurrency);if(!result.rate){res.status(404).json({error:'No contract rate is configured for this corridor.',code:'NOT_FOUND'});return;}res.json(result);}catch(e){next(e);}});
rampControlRouter.get('/providers/:operator',async(req,res,next)=>{try{const current=await context(req,res,'ramp_transactions:read');if(!current)return;const operator=stellarAddressSchema.safeParse(String(req.params.operator));if(!operator.success){res.status(400).json({error:'Enter a valid Stellar provider address.',code:'VALIDATION_ERROR'});return;}const result=await registeredProvider(controlNetwork(current.organization.platformMode),operator.data);if(!result.provider){res.status(404).json({error:'Provider is not registered.',code:'NOT_FOUND'});return;}res.json(result);}catch(e){next(e);}});

rampControlRouter.use((error:unknown,_req:Request,res:Response,_next:unknown)=>{if(error instanceof RampError){res.status(error.status).json({error:error.message,code:error.code});return;}console.error('[ramp-control] request failed',{error:error instanceof Error?error.message:'Unknown error'});res.status(500).json({error:'The ramp operation could not be completed.',code:'RAMP_INTERNAL_ERROR'});});
