import { randomUUID } from "node:crypto";
import { Router, type Request, type Response } from "express";
import { z } from "zod";

import { config } from "../config.js";
import { beginLogin, beginPasswordReset, createSessionFromOtp, register, resendOtp, resetPassword, revokeSession, selectOrganization, sessionResponseWithFreshCsrf, verifyCsrf, verifyEmailOtp } from "../auth/authService.js";
import { normalizeEmail, passwordPolicyError } from "../auth/security.js";

export const authRouter = Router();
const attempts = new Map<string,{count:number;resetAt:number}>();

function ip(request:Request):string{return request.ip||request.socket.remoteAddress||"unknown";}
function requestId(request:Request):string{return typeof request.headers["x-request-id"]==="string"?request.headers["x-request-id"]:randomUUID();}
function rateLimit(request:Request,response:Response,key:string,maximum:number):boolean{const now=Date.now();const identity=`${key}:${ip(request)}`;const current=attempts.get(identity);if(!current||current.resetAt<=now){attempts.set(identity,{count:1,resetAt:now+60_000});return true;}if(current.count>=maximum){response.setHeader("Retry-After",String(Math.ceil((current.resetAt-now)/1000)));response.status(429).json({error:"Too many requests. Try again later.",code:"RATE_LIMITED"});return false;}current.count+=1;return true;}
function cookies(request:Request):Record<string,string>{const result:Record<string,string>={};for(const part of (request.headers.cookie??"").split(";")){const index=part.indexOf("=");if(index>0)result[decodeURIComponent(part.slice(0,index).trim())]=decodeURIComponent(part.slice(index+1).trim());}return result;}
function sessionToken(request:Request):string|null{return cookies(request)[config.AUTH_SESSION_COOKIE_NAME]??null;}
function setSessionCookie(response:Response,token:string):void{const secure=config.APP_ENV==="production"?"; Secure":"";const maxAge=config.AUTH_SESSION_TTL_HOURS*3600;response.append("Set-Cookie",`${config.AUTH_SESSION_COOKIE_NAME}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${secure}`);}
function clearSessionCookie(response:Response):void{const secure=config.APP_ENV==="production"?"; Secure":"";response.append("Set-Cookie",`${config.AUTH_SESSION_COOKIE_NAME}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${secure}`);}
async function requireCsrf(request:Request,response:Response):Promise<string|null>{const token=sessionToken(request);const csrf=typeof request.headers["x-csrf-token"]==="string"?request.headers["x-csrf-token"]:"";if(!token||!csrf||!(await verifyCsrf(token,csrf))){response.status(403).json({error:"The security token is missing or invalid.",code:"CSRF_INVALID"});return null;}return token;}

const signupSchema=z.object({email:z.string().email(),password:z.string(),confirmPassword:z.string(),firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),phone:z.string().trim().min(5).max(40),legalName:z.string().trim().min(2).max(200),tradingName:z.string().trim().max(200).optional(),registrationCountry:z.string().trim().min(2).max(2),operatingCountry:z.string().trim().min(2).max(2),acceptedTerms:z.literal(true)}).superRefine((value,ctx)=>{if(value.password!==value.confirmPassword)ctx.addIssue({code:"custom",path:["confirmPassword"],message:"Passwords do not match."});const error=passwordPolicyError(value.password);if(error)ctx.addIssue({code:"custom",path:["password"],message:error});});

for(const [path,type] of [["/signup/business","BUSINESS"],["/signup/partner","SETTLEMENT_PARTNER"]] as const){authRouter.post(path,async(request,response)=>{if(!rateLimit(request,response,"signup",5))return;const parsed=signupSchema.safeParse(request.body);if(!parsed.success){response.status(400).json({error:"Review the highlighted fields.",code:"VALIDATION_ERROR",fieldErrors:Object.fromEntries(parsed.error.issues.map((issue)=>[String(issue.path[0]??"form"),issue.message]))});return;}try{const challenge=await register({...parsed.data,email:normalizeEmail(parsed.data.email),type,ip:ip(request),requestId:requestId(request)});response.status(201).json(challenge);}catch(error){if(error instanceof Error&&"code" in error&&(error as {code?:string}).code==="23505"){response.status(409).json({error:"Unable to create this account. Sign in or recover access if an account already exists.",code:"ACCOUNT_EXISTS"});return;}console.error("[auth] signup failed",{requestId:requestId(request),error:error instanceof Error?error.message:"Unknown error"});response.status(500).json({error:"We could not create the account.",code:"SIGNUP_FAILED"});}});}

authRouter.post("/verify-email",async(request,response)=>{if(!rateLimit(request,response,"verify-email",10))return;const parsed=z.object({challengeId:z.string().uuid(),code:z.string().regex(/^\d{6}$/)}).safeParse(request.body);if(!parsed.success){response.status(400).json({error:"Enter the six-digit verification code.",code:"VALIDATION_ERROR"});return;}const valid=await verifyEmailOtp(parsed.data.challengeId,parsed.data.code,{ip:ip(request),requestId:requestId(request)});if(!valid){response.status(400).json({error:"The code is invalid or has expired.",code:"OTP_INVALID"});return;}response.json({verified:true});});

authRouter.post("/login",async(request,response)=>{if(!rateLimit(request,response,"login",8))return;const parsed=z.object({email:z.string().email(),password:z.string().min(1)}).safeParse(request.body);if(!parsed.success){response.status(400).json({error:"Enter a valid email and password.",code:"VALIDATION_ERROR"});return;}const challenge=await beginLogin(parsed.data.email,parsed.data.password,ip(request));if(!challenge){response.status(401).json({error:"The email or password is incorrect, or this account cannot sign in.",code:"INVALID_CREDENTIALS"});return;}response.json(challenge);});

authRouter.post("/verify-otp",async(request,response)=>{if(!rateLimit(request,response,"verify-otp",10))return;const parsed=z.object({challengeId:z.string().uuid(),code:z.string().regex(/^\d{6}$/)}).safeParse(request.body);if(!parsed.success){response.status(400).json({error:"Enter the six-digit verification code.",code:"VALIDATION_ERROR"});return;}const session=await createSessionFromOtp(parsed.data.challengeId,parsed.data.code,{ip:ip(request),userAgent:request.headers["user-agent"],requestId:requestId(request)});if(!session){response.status(400).json({error:"The code is invalid or has expired.",code:"OTP_INVALID"});return;}setSessionCookie(response,session.token);response.json(session.response);});

authRouter.post("/otp/resend",async(request,response)=>{if(!rateLimit(request,response,"otp-resend",5))return;const parsed=z.object({challengeId:z.string().uuid()}).safeParse(request.body);if(!parsed.success){response.status(400).json({error:"The challenge is invalid.",code:"VALIDATION_ERROR"});return;}const challenge=await resendOtp(parsed.data.challengeId,ip(request));if(!challenge){response.status(429).json({error:"A new code cannot be issued yet.",code:"OTP_RESEND_UNAVAILABLE"});return;}response.json(challenge);});

authRouter.post("/forgot-password",async(request,response)=>{if(!rateLimit(request,response,"forgot-password",5))return;const parsed=z.object({email:z.string().email()}).safeParse(request.body);if(parsed.success){const challenge=await beginPasswordReset(parsed.data.email,ip(request));response.json({accepted:true,...(challenge&&config.APP_ENV==="development"?{challenge}: {})});return;}response.json({accepted:true});});
authRouter.post("/reset-password",async(request,response)=>{if(!rateLimit(request,response,"reset-password",8))return;const parsed=z.object({challengeId:z.string().uuid(),code:z.string().regex(/^\d{6}$/),password:z.string()}).safeParse(request.body);const policy=parsed.success?passwordPolicyError(parsed.data.password):"Invalid request.";if(!parsed.success||policy){response.status(400).json({error:policy??"Invalid request.",code:"VALIDATION_ERROR"});return;}const valid=await resetPassword(parsed.data.challengeId,parsed.data.code,parsed.data.password,{ip:ip(request),requestId:requestId(request)});if(!valid){response.status(400).json({error:"The code is invalid or has expired.",code:"OTP_INVALID"});return;}response.json({reset:true});});

authRouter.get("/session",async(request,response)=>{const token=sessionToken(request);const session=token?await sessionResponseWithFreshCsrf(token):null;if(!session){response.status(401).json({error:"Authentication is required.",code:"UNAUTHENTICATED"});return;}response.json(session);});
authRouter.post("/session/organization",async(request,response)=>{const token=await requireCsrf(request,response);if(!token)return;const parsed=z.object({organizationId:z.string().uuid()}).safeParse(request.body);if(!parsed.success||!(await selectOrganization(token,parsed.data.organizationId))){response.status(403).json({error:"You do not have access to that organization.",code:"ORGANIZATION_DENIED"});return;}response.json(await sessionResponseWithFreshCsrf(token));});
authRouter.post("/logout",async(request,response)=>{const token=await requireCsrf(request,response);if(!token)return;await revokeSession(token);clearSessionCookie(response);response.status(204).end();});
