import { randomUUID } from "node:crypto";
import { Router, type Request, type Response } from "express";
import { z } from "zod";
import type { BusinessComplianceProfile } from "@oynk/shared";
import { getSessionByToken, verifyCsrf } from "../auth/authService.js";
import { config } from "../config.js";
import { pool } from "../db/pool.js";

export const complianceRouter = Router();

function sessionToken(request: Request): string | null { for (const part of (request.headers.cookie ?? "").split(";")) { const [name, ...value] = part.trim().split("="); if (name === config.AUTH_SESSION_COOKIE_NAME) return decodeURIComponent(value.join("=")); } return null; }
async function context(request: Request, response: Response, permission: "compliance:read" | "compliance:submit", csrf = false) { const token = sessionToken(request); const session = token ? await getSessionByToken(token) : null; if (!token || !session?.organization) { response.status(401).json({ error: "Authentication is required.", code: "UNAUTHENTICATED" }); return null; } if (!session.organization.permissions.includes(permission)) { response.status(403).json({ error: "You do not have permission to update verification information.", code: "PERMISSION_DENIED" }); return null; } if (csrf) { const value = typeof request.headers["x-csrf-token"] === "string" ? request.headers["x-csrf-token"] : ""; if (!value || !(await verifyCsrf(token, value))) { response.status(403).json({ error: "The security token is missing or invalid.", code: "CSRF_INVALID" }); return null; } } return { session, organization: session.organization }; }

const profileSchema = z.object({ legalName: z.string().trim().min(2).max(200), tradingName: z.string().trim().max(200), organizationType: z.string().trim().min(2).max(100), registrationNumber: z.string().trim().min(2).max(100), registrationCountry: z.string().regex(/^[A-Z]{2}$/), incorporationDate: z.string().date(), taxIdentificationNumber: z.string().trim().min(2).max(100), website: z.union([z.literal(""), z.string().url()]), industry: z.string().trim().min(2).max(120), businessDescription: z.string().trim().min(20).max(2000), addressLine1: z.string().trim().min(3).max(200), addressLine2: z.string().trim().max(200), city: z.string().trim().min(2).max(120), region: z.string().trim().min(2).max(120), postalCode: z.string().trim().min(2).max(30), addressCountry: z.string().regex(/^[A-Z]{2}$/), expectedMonthlyVolume: z.string().regex(/^\d+(\.\d{1,2})?$/), expectedMonthlyTransactions: z.string().regex(/^\d+$/), sourceOfFunds: z.string().trim().min(3).max(500) });

complianceRouter.get("/business", async (request, response) => { const current = await context(request, response, "compliance:read"); if (!current) return; const result = await pool.query(`SELECT o.legal_name,o.trading_name,o.registration_country,p.* FROM organizations o LEFT JOIN business_compliance_profiles p ON p.organization_id=o.id WHERE o.id=$1`, [current.organization.id]); const row = result.rows[0]; const profile: BusinessComplianceProfile = { legalName: row.legal_name, tradingName: row.trading_name ?? "", organizationType: row.organization_type ?? "", registrationNumber: row.registration_number ?? "", registrationCountry: row.registration_country ?? "", incorporationDate: row.incorporation_date ? new Date(row.incorporation_date).toISOString().slice(0,10) : "", taxIdentificationNumber: row.tax_identification_number ?? "", website: row.website ?? "", industry: row.industry ?? "", businessDescription: row.business_description ?? "", addressLine1: row.address_line_1 ?? "", addressLine2: row.address_line_2 ?? "", city: row.city ?? "", region: row.region ?? "", postalCode: row.postal_code ?? "", addressCountry: row.address_country ?? "", expectedMonthlyVolume: row.expected_monthly_volume?.toString() ?? "", expectedMonthlyTransactions: row.expected_monthly_transactions?.toString() ?? "", sourceOfFunds: row.source_of_funds ?? "", status: row.status ?? "DRAFT", updatedAt: row.updated_at?.toISOString() ?? null }; response.json(profile); });

complianceRouter.put("/business", async (request, response) => { const current = await context(request, response, "compliance:submit", true); if (!current) return; const parsed = profileSchema.safeParse(request.body); if (!parsed.success) { response.status(400).json({ error: "Review the highlighted information.", code: "VALIDATION_ERROR", fieldErrors: Object.fromEntries(parsed.error.issues.map((issue) => [String(issue.path[0] ?? "form"), issue.message])) }); return; } const value = parsed.data; const client = await pool.connect(); try { await client.query("BEGIN"); await client.query(`UPDATE organizations SET legal_name=$2,trading_name=NULLIF($3,''),registration_country=$4,updated_at=NOW() WHERE id=$1`, [current.organization.id,value.legalName,value.tradingName,value.registrationCountry]); await client.query(`INSERT INTO business_compliance_profiles(organization_id,organization_type,registration_number,incorporation_date,tax_identification_number,website,industry,business_description,address_line_1,address_line_2,city,region,postal_code,address_country,expected_monthly_volume,expected_monthly_transactions,source_of_funds,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT(organization_id) DO UPDATE SET organization_type=$2,registration_number=$3,incorporation_date=$4,tax_identification_number=$5,website=$6,industry=$7,business_description=$8,address_line_1=$9,address_line_2=$10,city=$11,region=$12,postal_code=$13,address_country=$14,expected_monthly_volume=$15,expected_monthly_transactions=$16,source_of_funds=$17,updated_by=$18,updated_at=NOW()`, [current.organization.id,value.organizationType,value.registrationNumber,value.incorporationDate,value.taxIdentificationNumber,value.website,value.industry,value.businessDescription,value.addressLine1,value.addressLine2,value.city,value.region,value.postalCode,value.addressCountry,value.expectedMonthlyVolume,value.expectedMonthlyTransactions,value.sourceOfFunds,current.session.user.id]); await client.query(`INSERT INTO audit_logs(id,actor_user_id,organization_id,action,resource_type,resource_id,result,metadata) VALUES($1,$2,$3,'COMPLIANCE_DRAFT_SAVED','BUSINESS_COMPLIANCE',$3,'SUCCESS',$4)`, [randomUUID(),current.session.user.id,current.organization.id,{fields:Object.keys(value)}]); await client.query("COMMIT"); response.json({ ...value, status: "DRAFT", updatedAt: new Date().toISOString() } satisfies BusinessComplianceProfile); } catch (error) { await client.query("ROLLBACK"); console.error("[compliance] draft save failed", { organizationId: current.organization.id, error: error instanceof Error ? error.message : "Unknown error" }); response.status(500).json({ error: "We could not save the business information.", code: "COMPLIANCE_SAVE_FAILED" }); } finally { client.release(); } });
